import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Shield, FileText, Users, TrendingUp, CheckCircle } from 'lucide-react'
import AuthLeftPanel from '@/components/custom/AuthLeftPanel'

const features = [
  {
    icon: FileText,
    title: 'Centralized study management',
    description: 'Submit, track, and receive your PSG and PV sleep studies in one place.',
  },
  {
    icon: Shield,
    title: 'End-to-end encryption',
    description: 'All patient data is encrypted at rest with AES-256-GCM. GDPR compliant.',
  },
  {
    icon: Users,
    title: 'Collaborative workspace',
    description: 'Real-time comments between clients and agents for seamless communication.',
  },
  {
    icon: TrendingUp,
    title: 'Clinical-grade reports',
    description: 'Validated PDF reports generated by certified sleep specialists.',
  },
]

const trialIncludes = [
  '30-day free trial, no credit card required',
  'Unlimited study submissions',
  'Full access to agent communication',
  'PDF report downloads',
  'Secure encrypted storage',
]

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-[#f8fafc]">
      {/* Header */}
      <header className="border-b border-gray-100 bg-white/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div>
            <span className="text-2xl font-display text-teal">SomnoConnect</span>
            <span className="ml-2 text-[8px] tracking-[2px] uppercase text-gray-400 font-heading">BY SOMNOVENTIS</span>
          </div>
          <nav className="flex items-center gap-4">
            <Link
              href="/auth/login"
              className="text-sm text-gray-600 hover:text-midnight font-medium transition-colors"
            >
              Sign in
            </Link>
            <Button asChild className="bg-teal hover:bg-teal/90 text-white rounded-xl font-heading text-sm">
              <Link href="/auth/trial">Start free trial</Link>
            </Button>
          </nav>
        </div>
      </header>

      {/* Hero */}
      <section className="max-w-6xl mx-auto px-6 py-20 lg:py-28 grid lg:grid-cols-2 gap-12 items-center">
        <div>
          <div className="inline-flex items-center gap-2 bg-teal/10 text-teal text-xs font-heading uppercase tracking-widest px-3 py-1.5 rounded-full mb-6">
            <CheckCircle className="h-3.5 w-3.5" />
            30-day free trial
          </div>
          <h1 className="text-5xl lg:text-6xl font-display text-midnight leading-tight mb-6">
            Sleep studies,<br />
            <span className="text-teal">simplified.</span>
          </h1>
          <p className="text-gray-500 font-body text-lg leading-relaxed mb-8 max-w-lg">
            The secure medical platform designed for sleep clinics. Submit your studies, collaborate with specialists, and receive validated clinical reports — all in one place.
          </p>
          <div className="flex flex-col sm:flex-row gap-3">
            <Button
              asChild
              size="lg"
              className="bg-teal hover:bg-teal/90 text-white font-heading rounded-xl px-8 hover:shadow-lg hover:-translate-y-px transition-all"
            >
              <Link href="/auth/trial">Start free trial</Link>
            </Button>
            <Button
              asChild
              size="lg"
              variant="outline"
              className="border-2 border-midnight/20 text-midnight font-heading rounded-xl px-8 hover:border-teal hover:text-teal transition-all"
            >
              <Link href="/auth/login">Sign in</Link>
            </Button>
          </div>
          <p className="text-xs text-gray-400 font-body mt-4">No credit card required · Cancel anytime</p>
        </div>

        {/* Feature card preview */}
        <div className="relative hidden lg:block">
          <div className="bg-midnight rounded-2xl p-8 shadow-2xl text-white relative overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-br from-teal/10 to-transparent pointer-events-none" />
            <p className="text-sand/40 text-[9px] tracking-[3px] uppercase font-heading mb-6">SomnoConnect</p>
            <div className="space-y-4">
              {['PSG Study — Patient REF-2024-001', 'PV Study — Patient REF-2024-002', 'PSG Study — Patient REF-2024-003'].map((study, i) => (
                <div key={i} className="flex items-center justify-between bg-white/5 rounded-xl px-4 py-3 border border-white/10">
                  <span className="text-sm text-sand/80 font-body">{study}</span>
                  <span className={`text-xs px-2 py-1 rounded-full font-heading ${
                    i === 0 ? 'bg-gold/20 text-gold' :
                    i === 1 ? 'bg-teal/20 text-teal' :
                    'bg-white/10 text-sand/60'
                  }`}>
                    {i === 0 ? 'Completed' : i === 1 ? 'In progress' : 'Pending'}
                  </span>
                </div>
              ))}
            </div>
            <div className="mt-6 pt-6 border-t border-white/10 flex items-center gap-2 text-xs text-sand/50 font-body">
              <Shield className="h-3.5 w-3.5 text-teal" />
              All data encrypted with AES-256-GCM
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="bg-white border-y border-gray-100 py-20">
        <div className="max-w-6xl mx-auto px-6">
          <h2 className="text-3xl font-display text-midnight text-center mb-3">Everything your clinic needs</h2>
          <p className="text-gray-500 font-body text-center mb-12">Built for sleep specialists and clinics who demand reliability and security.</p>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map(({ icon: Icon, title, description }) => (
              <div key={title} className="p-6 rounded-2xl border border-gray-100 hover:border-teal/30 hover:shadow-md transition-all group">
                <div className="w-10 h-10 rounded-xl bg-teal/10 flex items-center justify-center mb-4 group-hover:bg-teal/20 transition-colors">
                  <Icon className="h-5 w-5 text-teal" />
                </div>
                <h3 className="font-heading text-midnight font-semibold mb-2">{title}</h3>
                <p className="text-sm text-gray-500 font-body leading-relaxed">{description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Trial CTA */}
      <section className="max-w-6xl mx-auto px-6 py-20">
        <div className="bg-midnight rounded-3xl p-10 lg:p-14 grid lg:grid-cols-2 gap-10 items-center overflow-hidden relative">
          <div className="absolute inset-0 bg-gradient-to-br from-teal/10 via-transparent to-gold/5 pointer-events-none" />
          <div className="relative">
            <h2 className="text-4xl font-display text-sand mb-4 leading-tight">
              Start your free trial today
            </h2>
            <p className="text-sand/60 font-body leading-relaxed mb-6">
              Join sleep clinics already using SomnoConnect. Get full access for 30 days — no commitment, no credit card.
            </p>
            <Button
              asChild
              size="lg"
              className="bg-teal hover:bg-teal/90 text-white font-heading rounded-xl px-8 hover:shadow-lg hover:-translate-y-px transition-all"
            >
              <Link href="/auth/trial">Start free trial</Link>
            </Button>
          </div>
          <ul className="relative space-y-3">
            {trialIncludes.map((item) => (
              <li key={item} className="flex items-center gap-3 text-sand/80 font-body text-sm">
                <CheckCircle className="h-4 w-4 text-teal shrink-0" />
                {item}
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-100 py-8">
        <div className="max-w-6xl mx-auto px-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-gray-400 font-body">© {new Date().getFullYear()} SOMNOVENTIS. All rights reserved.</p>
          <div className="flex items-center gap-2 text-xs text-gray-400 font-body">
            <Shield className="h-3.5 w-3.5" />
            GDPR compliant · Encrypted medical data
          </div>
        </div>
      </footer>
    </div>
  )
}
